### ISSUE TITLE
Segmentation fault in compiler

### ISSUE THREAD

**Issue by hryx** [zig-lang/zig#946] opened 2018-04-23 00:59 UTC
Here is a short program which causes the compiler to be terminated due to a segfault:

https://gist.github.com/hryx/7961dce2317c7e588f85c4a5ea0dd296

(Sorry about my vague issue titles. Please feel free to rename once the cause is narrowed down.)

My setup: macOS 10.12.6, zig 0.2.0 (via Homebrew), fish 2.7.1. I ran zig build-exe main.zig.

**Comment by BraedonWooding** [comment] 2018-04-23 01:09
Exact same error message as #945 for me on master.  Seems to be same bug (still keep this open however since they are different cases).

In the mean time the following code will work on Zig :)
```
    pub fn to_char(self: &const Tile) u8 {
        switch (self.x) {
            0 => return '.',
            else => return 'x',
        }
    }
```
Try to avoid using '*' :).

**Comment by andrewrk** [comment] 2018-04-23 03:48
Duplicate of #945

**Closed by andrewrk** 2018-04-23 03:48 UTC
