### ISSUE TITLE
@import() should search for paths relative to the root zig file / location zig was invoked

### ISSUE THREAD

**Issue by zesterer** [zig-lang/zig#744] opened 2018-02-05 09:44 UTC
I have a fairly complex (or will have soon) codebase. I'd like to be able to copy code across different files in different parts of the project tree without changing all of the import references such that they look like `../../../foo.zig`.

It would be really nice if Zig also searched for files relative to either the directory that zig was invoked within or the location of the main Zig file.

Alternatively, it could be possible to use a compiler flag to specify additional root paths to search for Zig imports. Something akin to the `-I` flag implemented by most C compilers.

**Comment by andrewrk** [comment] 2018-02-05 13:10
duplicate of #216

**Closed by andrewrk** 2018-02-05 13:10 UTC
Labels: duplicate
