### ISSUE TITLE
Compiler crashes with "unreachable" when an extern fn references an undeclared type

### ISSUE THREAD

**Issue by tgschultz** [zig-lang/zig#724] opened 2018-01-27 07:39 UTC
```
pub extern fn CrashMeFunc() CrashMeType;

test "extern fn returns undeclared type" {
    var t = CrashMeFunc();
}
```

```
>zig test crashTest.zig
unreachable
```

Test was conducted on Windows 10 x64 using Zig 0.1.1.f7670882

**Comment by tiehuis** [comment] 2018-01-27 08:06
Duplicate of #722.

**Closed by tiehuis** 2018-01-27 08:06 UTC
Labels: bug
