### ISSUE TITLE
add general purpose allocator to standard library

### ISSUE THREAD

**Issue by andrewrk** [zig-lang/zig#511] opened 2017-10-01 14:42 UTC
We have `std.mem.IncrementingAllocator` but we also should have a general purpose allocator.

**Comment by PavelVozenilek** [comment] 2017-10-01 17:56
Before engaging in writing block allocator from scratch Zig could wrap one or more existing C allocators. The one I use is Doug Lea's malloc ( http://g.oswego.edu/dl/html/malloc.html ). The code had been maintained for some **30** years. Its API is feature rich and targets high performance use.

It is implemented as one file library, joy to use.

Sometimes the internet claims there are more modern and/or faster allocators. These claims are not accompanied by benchmarks, but could be correct in some situations: DL malloc doesn't use separate per-thread heaps.

Several other allocators are based on DL malloc, e.g. nedmalloc:  http://www.nedprod.com/programs/portable/nedmalloc/ .

**Comment by andrewrk** [comment] 2017-10-01 19:59
See also #480

**Comment by tiehuis** [comment] 2018-01-25 09:32
By the way, see here: https://github.com/tiehuis/zig-dlmalloc

Trying out a C -> zig conversion in small parts at a time. I've gutted a lot of the unrequired info and non-global defines/details to focus on a simple global non-threaded variant.

I'll see where I get, but it's likely I'll get this to a reasonably workable state since required the c allocator is probably ~80% of my use case for linking with libc.

**Comment by tiehuis** [comment] 2018-03-30 06:50
Duplicate of #480.

**Closed by tiehuis** 2018-03-30 06:50 UTC
Labels: enhancement
