### ISSUE TITLE
`zig run`

### ISSUE THREAD

**Issue by jfo** [zig-lang/zig#789] opened 2018-02-24 14:14 UTC
It would be nice to have a command that would build an executable in debug mode and execute it. I am using a workaround in my own workflow for this pattern but I was wondering if this sounds useful to anyone else or if there is already this functionality somewhere. Could easily be cached.

**Comment by andrewrk** [comment] 2018-02-24 17:21
Duplicate of #466

**Closed** 2018-02-24 17:21 UTC
