### ISSUE TITLE
comptime crash when attempting to access member of nonexistent symbol

### ISSUE THREAD

**Issue by tgschultz** [zig-lang/zig#936] opened 2018-04-21 00:53 UTC
```
test "comptime nonexistent symbol member access" {
    comptime { var x = doesnt_exist.whatever; }
}
```

**Comment by andrewrk** [comment] 2018-04-21 05:56
I believe this was caused by 6b4f6ebd89c4788fde09dd5cde17f3cb54c6c656 and fixed by 6e57243a79b08f37b80122f0eb24d073d6e2e95c.

**Closed by andrewrk** 2018-04-21 05:56 UTC
Labels: bug
